### Scaler標準化。
### MinMaxScaler將屬性縮放到 0~1
### StandardScaler保存訓練集中的參數（均值、標準差）直接使用其對象轉換測試集數據。

In [1]:
from sklearn.preprocessing import StandardScaler

In [2]:
data = [[-1,2],[-0.5,6],[0,10],[1,18]]

## 【原始套件】
### 此作業要模仿部分: StandardScaler

In [3]:
scaler = StandardScaler() 

In [4]:
#----fit----
scaler.fit(data)   

StandardScaler(copy=True, with_mean=True, with_std=True)

In [5]:
# mean_  對向量 做平均
scaler.mean_ 

array([-0.125,  9.   ])

In [7]:
# var_   對向量 做變異數
scaler.var_

array([ 0.546875, 35.      ])

In [8]:
#----transform---- 對向量 做標準差
scaler.transform(data) 

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [9]:
scaler.transform([[2,2]]) 

array([[ 2.87352447, -1.18321596]])

In [10]:
import numpy as np

##  【模擬】
### 試算類別中的 fit、transform，找出原計算方式

In [14]:
# fit--找scaler.mean_的原理
np.mean(data, axis=0)

array([-0.125,  9.   ])

In [15]:
#  fit--找scaler.var_的原理
np.var(data, axis=0)

array([ 0.546875, 35.      ])

In [16]:
# transform--找scaler.transform的原理調。 做成變異數
(np.array(data) - scaler.mean_ ) / (scaler.var_**0.5)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [17]:
 class MyStandardScaler: # 【　MyStandardScaler 此類別有以下功能　】 
    
    def __init__(self):                             #初始化定義
        self.mean = None
        self.var = None
        
    def fit(self,data):                            #self:慣例上，第一個傳self  #第二個傳data
        self.mean = np.mean(data, axis=0)
        self.var  = np.var(data, axis=0)
        
    def transform(self,data):
        return (np.array(data) - scaler.mean_ ) / (scaler.var_**0.5)
    
    def fit_transform(self,data):
        self.fit(data)
        return self.transform(data)

##    【測試模擬結果】

In [18]:
myscaler = MyStandardScaler()

In [19]:
myscaler.fit(data)   

In [20]:
myscaler.mean

array([-0.125,  9.   ])

In [21]:
myscaler.var

array([ 0.546875, 35.      ])

In [22]:
myscaler.transform(data)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [23]:
myscaler.transform([[2,2]])

array([[ 2.87352447, -1.18321596]])